runtime: python
env: flex
api_version: 1
threadsafe: true
entrypoint: gunicorn -b :$PORT run:app
runtime_config:
 python_version: 3

handlers:
- url: /
  script: flaskblog/templates/home.app
- url: /home
  script: flaskblog/templates/home.app
- url: /about
  script: flaskblog/templates/about.app
- url: /post/new
  script: flaskblog/templates/create_post.app
- url: /post/^([1-9][0-9]{0,2}|1000)$
  script: flaskblog/templates/post.app
- url: /post/^([1-9][0-9]{0,2}|1000)$
  script: flaskblog/templates/post.app
